server:
  port: 8081
spring:
  application:
    name: reggie-web-app # 应用名称
  datasource: # 数据源配置
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
#  redis
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/**.xml
  global-config:
    db-config:
        id-type: ASSIGN_ID # id生成策略类型

reggie:
  sms:
    key: LTAI5tJiegyFJgPii3prnZoU
    secret: LCo03eVRDQZH5CZn6fAVA9GhDDQEZ3
    sign-name: 阿里云短信测试
    template-code: SMS_154950909

